version: "2.4"
services:
  garrysmod:
    image: quay.io/rbreslow/garrysmodds:slim
    volumes:
      - ./src/speak:/var/lib/steam/.steam/steamapps/common/GarrysModDS/garrysmod/addons/speak
    stdin_open: true
    tty: true
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    command: [
      "-game garrysmod",
      "-maxplayers 16",
      "+gamemode sandbox",
      "+sv_password secret",
      "+map gm_construct"
    ]

  app:
    image: node:10-slim
    volumes:
      - ./src/app:/usr/local/src
      - ./src/speak/lua/speak/static:/usr/local/src/dist
    working_dir: /usr/local/src
    environment:
      - REACT_APP_GIT_COMMIT=${REACT_APP_GIT_COMMIT:-latest}
    command: yarn watch

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

  luacheck:
    image: quay.io/rbreslow/luacheck:0.23.0-1
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

  gmad:
    image: quay.io/rbreslow/garrysmodds:slim
    user: root
    environment:
      - LD_LIBRARY_PATH=./bin
    volumes:
      - ./dist:/usr/local/src/out
      - ./src/speak:/var/lib/steam/.steam/SteamApps/common/GarrysModDS/garrysmod/addons/speak
    entrypoint: ./bin/gmad_linux
