#!/bin/bash

set -e

if [[ -n "${SPEAK_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Start Source Dedicated Server (srcds).
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose run --rm --service-ports \
            garrysmod
    fi
fi
