#!/bin/bash

set -e

if [[ -n "${SPEAK_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Start SRCDS.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" = "--help" ]]; then
        usage
    else
        docker-compose up app garrysmod
    fi
fi
