#!/bin/bash

set -e

if [[ -n "${SPEAK_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Run tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Linting Lua sources"
        docker-compose \
            run --rm --no-deps \
            luacheck .

        echo "Linting JavaScript sources"
        docker-compose \
            run --rm --no-deps app \
            yarn lint
    fi
fi
