#!/bin/bash

set -e

if [[ -n "${SPEAK_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Update dependencies and static asset bundle.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Ensure container images are current
        docker-compose build --pull

        # Update Yarn dependencies
        docker-compose \
            run --rm --no-deps app \
            yarn install

        # Build static asset bundle
        docker-compose \
            run --rm --no-deps app \
            yarn run build
    fi
fi
