#!/bin/bash

set -e

if [[ -n "${SPEAK_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Watch files and recompile whenever they change.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose \
            run --rm --no-deps app \
            yarn run watch
    fi
fi
