name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2

      - run: ./scripts/cibuild
